feat: support IgnoreErrors and IgnoreTransactions client options
getsentry/sentry-go pull request #717
Opened 2023-09-14 15:27 UTC by greywolve

2023-09-15 08:22 UTC, tonyo approved these changes
LGTM, thanks 👍 

Could you just add a bit of PR description and link to the issue it's fixing/implementing?

2023-09-15 09:11 UTC, cleptric requested changes
We want to make sure this continues to work with the `ignoreErrorsIntegration` that is currently controlled via the `IgnoreErrors` option.

I would opt to make an `ignoreTransactionsIntegration`, as we can't remove the `ignoreErrorsIntegration`, as this would cause people issues for people using it today.

2023-09-15 09:32 UTC, greywolve commented
> We want to make sure this continues to work with the [`ignoreErrorsIntegration`](https://github.com/getsentry/sentry-go/blob/master/integrations.go#L120-L178) that is currently controlled via the `IgnoreErrors` option.
> 
> I suggest adding an `ignoreTransactionsIntegration`, as we can't remove the `ignoreErrorsIntegration`, which would cause issues for people using it today.

Hmm, my bad. I missed that `IgnoreErrors` was already a working integration. I'll rework this to just add an `IgnoreTransaction` integration, and not do any of the logic in `client.go`.

2023-09-15 20:42 UTC, greywolve commented
@cleptric rework done. :)

2023-09-18 19:59 UTC, cleptric approved these changes

2023-09-18 19:59 UTC, merged