feat(tracing): Add WithDescription SpanOption
getsentry/sentry-go pull request #751
Opened 2023-11-27 03:27 UTC by natikgadzhi

## Summary

This pull request adds `WithDescription` span option! Closes #739, thank you to @moneymikemd for the issue.

## Changes

- Disclaimer: I was just diving into the go SDK codebase, and was looking through the issue list for an easy way in. Please feel free to tell me to gtfo if that pull request is not all that useful. 
- I've added the `WithDescription` `SpanOption` that works similar to the existing `WithTransactionName` and friends.
- No unit tests. The other span options don't have them either. I would feel more confident adding tests for all span options — seems rather straightforward as well. Would you prefer that I do that in this PR, or a separate one? 

/cc @greywolve

2023-11-27 16:11 UTC, greywolve commented
@natikgadzhi thanks for the PR! Just need to fix a linting issue and this should be good. :)

2023-11-27 16:24 UTC, natikgadzhi commented
@greywolve I do have to admit, not setting up a formatter in a _Go_ project is kind of embarrasing. Fixed!

2023-11-27 17:15 UTC, greywolve commented
> @greywolve I do have to admit, not setting up a formatter in a _Go_ project is kind of embarrasing. Fixed!

Haha no problem, I forget this sometimes too :)

2023-11-27 17:18 UTC, natikgadzhi commented
Btw, perhaps worth setting up a .vscode/settings.json with custom formatter path to ensure gofmt -s by default?

2023-11-27 17:27 UTC, greywolve requested changes

2023-11-27 17:27 UTC, greywolve commented on tracing_test.go
> +		t.Fatalf("Description mismatch, expected span desc, got %v", span.Description)
```suggestion
		t.Fatalf("Description mismatch, got %v", span.Description)
```

Nitpick for consistency :)

2023-11-27 23:32 UTC, greywolve commented
> Btw, perhaps worth setting up a .vscode/settings.json with custom formatter path to ensure gofmt -s by default?

Not sure everyone uses vscode, but that could be useful for sure.

2023-11-28 10:49 UTC, cleptric approved these changes

2023-11-28 13:24 UTC, greywolve approved these changes

2023-11-28 13:24 UTC, merged