add SendEventWithContext method
getsentry/sentry-go pull request #824
Opened 2024-05-03 15:00 UTC by viglia

This will let us pass a context.Context when creating a new request with getRequestFromEvent.

2024-05-03 15:25 UTC, phacops requested changes

2024-05-03 15:25 UTC, phacops commented on transport.go
>  	return http.NewRequest(
You don't need to leave this here, just set `ctx = context.Background()` if it's `nil` and call `NewRequestWithContext`.

2024-05-03 16:32 UTC, cleptric commented on transport.go
> +func (t *HTTPTransport) SendEventWithContext(ctx context.Context, event *Event) {
Can we fix the grammar here please, even if it's just a copy of the old mistakes?

2024-05-03 16:33 UTC, cleptric reviewed
Could you add a bit more about the why?

2024-05-03 16:33 UTC, cleptric commented on transport.go
> +func (t *HTTPSyncTransport) SendEventWithContext(ctx context.Context, event *Event) {
Same here.

2024-05-06 13:54 UTC, phacops approved these changes

2024-05-06 17:05 UTC, merged